// <auto-generated />
using System;
using DGII.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGII.Infrastructure.Migrations
{
    [DbContext(typeof(DgiiDbContext))]
    [Migration("20250821205850_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DGII.Domain.Entities.ComprobanteFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("ContribuyenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("itbis18")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Comproba__3214EC0727DE92D3");

                    b.HasIndex("ContribuyenteId");

                    b.HasIndex("NCF")
                        .IsUnique();

                    b.ToTable("ComprobantesFiscales");
                });

            modelBuilder.Entity("DGII.Domain.Entities.Contribuyente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("estatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("rncCedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Contribu__3214EC070D5622E1");

                    b.HasIndex("estatus");

                    b.HasIndex("rncCedula")
                        .IsUnique();

                    b.ToTable("Contribuyentes");
                });

            modelBuilder.Entity("DGII.Domain.Entities.ComprobanteFiscal", b =>
                {
                    b.HasOne("DGII.Domain.Entities.Contribuyente", "Contribuyente")
                        .WithMany("ComprobantesFiscales")
                        .HasForeignKey("ContribuyenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ComprobantesFiscales_Contribuyentes");

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("DGII.Domain.Entities.Contribuyente", b =>
                {
                    b.Navigation("ComprobantesFiscales");
                });
#pragma warning restore 612, 618
        }
    }
}
